### ISSUE TITLE
🐛 Bug: Ersilia Python API on PY3.12

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#1520]
### Describe the bug.

Hi, 

I am trying to use the Ersilia Python API on PY3.12, while this worked before it seems to have broken down. It happens both in my Mac and my Ubuntu set ups. Works fine on py3.11
@DhanshreeA not a problem with the CLI, so this definitely calls for a specific test of the Python API, which we just decided not to include?

```
Python 3.12.8 | packaged by Anaconda, Inc. | (main, Dec 11 2024, 16:31:09) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ersilia import ErsiliaModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gturon/github/ersilia/ersilia/__init__.py", line 34, in <module>
    from .core.modelbase import ModelBase
  File "/home/gturon/github/ersilia/ersilia/core/modelbase.py", line 6, in <module>
    from ..hub.content.slug import Slug
  File "/home/gturon/github/ersilia/ersilia/hub/content/slug.py", line 4, in <module>
    from .card import ModelCard
  File "/home/gturon/github/ersilia/ersilia/hub/content/card.py", line 8, in <module>
    from ...auth.auth import Auth
  File "/home/gturon/github/ersilia/ersilia/auth/auth.py", line 7, in <module>
    from github import Github
ImportError: cannot import name 'Github' from 'github' (unknown location)
```

If helpful, this is the package list in my conda env for ersilia on Ubuntu. [ersiliapy312.txt](https://github.com/user-attachments/files/18520133/ersiliapy312.txt)

Clearly problematic for my ZairaChem installation which was on PY3.12 already

### Operating environment

Ubuntu 24.04 LTS

**Comment by DhanshreeA** [comment]
@GemmaTuron can you show me what you see in the file `ersilia/auth/auth.py` from this installation?

Here's what I see:

```python
import os
from pathlib import Path

import yaml

try:
    from github import Github
    from github.GithubException import UnknownObjectException
except ModuleNotFoundError:
    Github = None
    UnknownObjectException = None
```

And I am unable to reproduce this error in Python 3.12 with the API, in conda or otherwise. The thing is, this code should automatically be saved by the `except ModuleNotFoundError`, but from the logs shared I see an `ImportError` instead of `ModuleNotFoundError` so that's very strange.

**Comment by GemmaTuron** [comment]
This is what I have:
```
import os
from pathlib import Path

import yaml

try:
    from github import Github
    from github.GithubException import UnknownObjectException
except ModuleNotFoundError:
    Github = None
    UnknownObjectException = None

```
I did pull ersilia at the start of the day so it should be the same as online

**Comment by GemmaTuron** [comment]
I have py 3.12.8 in those envs. Just tested py3.12.7 and it does not happen so it is a python problem

**Comment by DhanshreeA** [comment]
@GemmaTuron that's even weird, I am using Python 3.12.8 in both conda and non conda envs. Still unable to reproduce this. However, I have pushed a hotfix to unblock this - catching both the exceptions (ModuleNotFoundError, and ImportError). That should take care of this. I'll dig into the WHY of this issue later.

**Comment by GemmaTuron** [comment]
wait what? It stopped happening? I am now at a loss I have reproduced the error on my  local Ubuntu, on the workstation and on the Mac... Now it does not happpen on my ubuntu (see) but it happens on my mac still
```
(ersiliatest) gturon@pujarnol:~/github/ersilia-os/ersilia$ python
Python 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:27:36) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ersilia import ErsiliaModel
>>> exit()
(ersiliatest) gturon@pujarnol:~/github/ersilia-os/ersilia$ conda activate ersilia
(ersilia) gturon@pujarnol:~/github/ersilia-os/ersilia$ python
Python 3.12.8 | packaged by Anaconda, Inc. | (main, Dec 11 2024, 16:31:09) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ersilia import ErsiliaModel
>>> 
```

**Comment by DhanshreeA** [comment]
@GemmaTuron did you just pull again? Because I just pushed that fix I mentioned a comment above.

**Comment by DhanshreeA** [comment]
Wow this is just so weird XD

**Comment by GemmaTuron** [comment]
wow I don't know
let's not lose time on this. IF it happens consistently we'll investigate more.
Thanks for the help!
